name: gba-data-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5
  - numpy=1.24
  - matplotlib=3.7
  - seaborn=0.12
  - scikit-learn=1.3
  - scipy=1.10
  - jupyter
  - geopandas
  - libpysal
  - pip
  - pip:
    - factor-analyzer>=0.4.1
    - dcor>=0.6.2
    - statsmodels>=0.14.0
    - tqdm>=4.65.0
